[Messenger]
apkmirror-dlurl = "https://apkmirror.com/apk/facebook-2/messenger/"

[Tiktok]
apkmirror-dlurl = "https://apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "inotia00 ReVanced"
apkmirror-arch = "arm64-v8a"
build-mode = "module"
included-patches = "'Add splash animation' 'Custom playback speed' 'Disable shorts on startup' 'Enable external browser' 'Enable minimized playback' 'Enable open links directly' 'Enable wide search bar' 'Hide channel watermark' 'Hide crowdfunding box' 'Hide general ads' 'Hide video ads' 'MaterialYou' 'Return YouTube Dislike' 'Sanitize sharing links' 'SponsorBlock' 'Spoof app version' 'Spoof device dimensions' 'Spoof player parameters' 'Swipe controls'"
exclusive-patches = true

[Twitch]
apkmirror-dlurl = "https://apkmirror.com/apk/twitch-interactive-inc/twitch/"

[Twitter]
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"

[Reddit]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"

[Instagram]
apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram/"

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"

